package com.fellowlodge.api.tools;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * One-off tool that exports legacy SQLite data into PostgreSQL-compatible SQL.
 *
 * Usage:
 *   mvn -q compile exec:java \
 *     -Dexec.mainClass=com.fellowlodge.api.tools.SqliteToPostgresMigrator \
 *     -Dexec.args="--sqlite=path/to/fellowlodge.db --out=migration.sql"
 *
 * The generated file is a plain SQL script with INSERT statements emitted in
 * foreign-key dependency order. Run it against Supabase via the SQL Editor or
 * psql:
 *   psql "$SUPABASE_CONNECTION_STRING" -f migration.sql
 */
public final class SqliteToPostgresMigrator {

    static final List<String> TABLE_ORDER = List.of(
            "roles", "users", "staff", "guests", "room_types", "rooms",
            "reservations", "check_ins", "check_outs", "payments", "invoices",
            "maintenance", "audit_logs", "settings", "housekeeping", "notifications");

    private SqliteToPostgresMigrator() {
    }

    public static void main(String[] args) throws Exception {
        Map<String, String> options = parseArgs(args);
        String sqlitePath = options.get("--sqlite");
        if (sqlitePath == null) {
            throw new IllegalArgumentException("Missing required option --sqlite=<path>");
        }
        String outPath = options.getOrDefault("--out", "fellowlodge-sqlite-migration.sql");
        List<String> tables = options.containsKey("--tables")
                ? List.of(options.get("--tables").split(","))
                : TABLE_ORDER;

        String sql = generate(Path.of(sqlitePath), tables);
        Files.writeString(Path.of(outPath), sql, StandardCharsets.UTF_8);
        System.out.println("Migration script written to " + outPath);
    }

    static String generate(Path sqlitePath, List<String> tables) {
        StringBuilder out = new StringBuilder();
        out.append("-- ====================================================================\n")
                .append("-- FELLOW LODGE - SQLite to PostgreSQL data migration\n")
                .append("-- Generated by SqliteToPostgresMigrator from ").append(sqlitePath.getFileName()).append("\n")
                .append("-- Emitted in foreign-key dependency order.\n")
                .append("-- ====================================================================\n")
                .append("BEGIN;\n\n");

        Set<String> requested = new LinkedHashSet<>(tables);
        try (Connection conn = DriverManager.getConnection("jdbc:sqlite:" + sqlitePath)) {
            for (String table : TABLE_ORDER) {
                if (requested.contains(table) && tableExists(conn, table)) {
                    appendTable(out, conn, table);
                }
            }
        } catch (SQLException e) {
            throw new IllegalStateException("Failed to read SQLite database " + sqlitePath, e);
        }

        out.append("COMMIT;\n");
        return out.toString();
    }

    private static boolean tableExists(Connection conn, String table) throws SQLException {
        try (ResultSet rs = conn.getMetaData().getTables(null, null, table, new String[]{"TABLE"})) {
            return rs.next();
        }
    }

    private static void appendTable(StringBuilder out, Connection conn, String table) throws SQLException {
        String quoted = "\"" + table + "\"";
        try (Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery("SELECT * FROM " + quoted + " LIMIT 0")) {
            ResultSetMetaData meta = rs.getMetaData();
            int columnCount = meta.getColumnCount();

            List<String> columns = new ArrayList<>(columnCount);
            for (int i = 1; i <= columnCount; i++) {
                columns.add(meta.getColumnLabel(i));
            }

            out.append("-- ").append(table).append(" (")
                    .append(columns.stream().map(c -> "\"" + c + "\"").reduce((a, b) -> a + ", " + b).orElse(""))
                    .append(")\n");
            String columnList = columns.stream()
                    .map(c -> "\"" + c + "\"")
                    .reduce((a, b) -> a + ", " + b)
                    .orElse("");

            int rows = 0;
            try (Statement full = conn.createStatement();
                 ResultSet data = full.executeQuery("SELECT * FROM " + quoted)) {
                while (data.next()) {
                    List<String> values = new ArrayList<>(columnCount);
                    for (int i = 1; i <= columnCount; i++) {
                        values.add(format(data.getObject(i)));
                    }
                    out.append("INSERT INTO ").append(quoted).append(" (")
                            .append(columnList).append(") VALUES (")
                            .append(String.join(", ", values)).append(");\n");
                    rows++;
                }
            }
            System.out.printf("  %-16s %d rows%n", table, rows);
            out.append("\n");
        }
    }

    private static String format(Object value) {
        if (value == null) {
            return "NULL";
        }
        if (value instanceof Number) {
            return value.toString();
        }
        return "'" + value.toString().replace("'", "''") + "'";
    }

    private static Map<String, String> parseArgs(String[] args) {
        java.util.HashMap<String, String> options = new java.util.HashMap<>();
        for (String arg : args) {
            int eq = arg.indexOf('=');
            if (eq > 0) {
                options.put(arg.substring(0, eq), arg.substring(eq + 1));
            } else {
                options.put(arg, "");
            }
        }
        return options;
    }
}
